# Generated by Django 2.1.7 on 2019-03-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('c_or_s', models.CharField(max_length=20, verbose_name='投诉建议')),
                ('content', models.TextField(max_length=250, verbose_name='内容')),
                ('is_process', models.BooleanField(default=False, verbose_name='是否处理')),
                ('process_result', models.TextField(default='', max_length=250, verbose_name='处理结果')),
            ],
        ),
    ]
