# Generated by Django 2.1.7 on 2019-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('order_by', models.PositiveIntegerField(verbose_name='序号')),
                ('contents', models.TextField(blank=True)),
            ],
        ),
    ]
