# Generated by Django 2.1.7 on 2019-05-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'ordering': ('order_by',), 'verbose_name': '文章'},
        ),
    ]
