# Generated by Django 2.1.7 on 2019-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20190512_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': '品类'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ('product',), 'verbose_name': 'ProductPrice', 'verbose_name_plural': '自定义价格'},
        ),
        migrations.AlterModelOptions(
            name='productpricegroup',
            options={'ordering': ('name',), 'verbose_name': 'PriceGroup', 'verbose_name_plural': '价格组'},
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='库存'),
        ),
    ]
