# Generated by Django 2.1.7 on 2019-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_tag_id', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='企业号标签ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='企业号个人账号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat_tag',
            field=models.ManyToManyField(to='login.WechatTag'),
        ),
    ]
