# Generated by Django 2.1.7 on 2019-05-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190513_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechattag',
            name='wechat_tag_name',
            field=models.CharField(default='dingdan ', max_length=25, verbose_name='企业号标签名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechattag',
            name='wechat_tag_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='企业号标签ID'),
        ),
    ]
