# Generated by Django 2.1.7 on 2019-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190512_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
