# Generated by Django 2.1.7 on 2019-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190514_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False, verbose_name='是否发货'),
        ),
    ]
